name: ROS2 Humble Simulation CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Cleanup old ROS keys/sources
      - name: Cleanup old ROS keys and sources
        run: |
          sudo rm -f /etc/apt/sources.list.d/ros2-latest.list
          sudo rm -f /etc/apt/trusted.gpg.d/ros-archive-key.gpg || true

      # Step 3: Add updated ROS2 GPG key and repository
      - name: Add updated ROS2 GPG key
        run: |
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | gpg --dearmor | sudo tee /usr/share/keyrings/ros-archive-keyring.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list
          sudo apt update

      # Step 4: Setup ROS2 Humble
      - name: Setup ROS2 Humble
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble

      # Step 5: Cache rosdep for faster builds
      - name: Cache rosdep
        uses: actions/cache@v3
        with:
          path: ~/.ros/rosdep/sources.cache
          key: ${{ runner.os }}-rosdep-cache

      # Step 6: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-rosdep python3-colcon-common-extensions python3-pip
          pip3 install --user black isort
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # Step 7: Format code with black and isort
      - name: Format Python code
        run: |
          python3 -m isort src test
          python3 -m black src test

      # Step 8: Build workspace
      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

      # Step 9: Run tests
      - name: Run tests
        run: |
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
