name: ROS2 Humble Simulation CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Remove any old ROS keys and sources to prevent exit code 100
      - name: Remove old ROS keys and sources
        run: |
          sudo rm -f /etc/apt/sources.list.d/ros2-latest.list
          sudo rm -f /etc/apt/trusted.gpg.d/ros-archive-key.gpg || true

      # Step 3: Setup ROS2 Humble
      - name: Setup ROS2 Humble
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble

      # Step 4: Cache rosdep sources to speed up builds
      - name: Cache rosdep
        uses: actions/cache@v3
        with:
          path: ~/.ros/rosdep/sources.cache
          key: ${{ runner.os }}-rosdep-cache

      # Step 5: Install ROS2 workspace dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-rosdep python3-colcon-common-extensions
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # Step 6: Build ROS2 workspace
      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

      # Step 7: Run tests
      - name: Run tests
        run: |
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose

