name: ROS2 Humble CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ROS2 Humble
        run: |
          sudo apt update && sudo apt install -y curl gnupg2 lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
            http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep python3-pip
          sudo rosdep init || true
          rosdep update

      - name: Upgrade Python build tools
        run: |
          python3 -m pip install --upgrade pip setuptools wheel colcon-common-extensions

      - name: Install Python formatters
        run: |
          python3 -m pip install black isort

      - name: Install ROS dependencies
        run: |
          source /opt/ros/humble/setup.bash
          rosdep install --from-paths src --ignore-src -r -y

      - name: Auto-format Python code
        run: |
          find src -name "*.py" | xargs python3 -m isort
          find src -name "*.py" | xargs python3 -m black

      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          python3 -m pip install --upgrade setuptools
          colcon build --symlink-install

      - name: Run tests
        run: |
          source install/setup.bash
          colcon test
          colcon test-result --verbose
