name: ROS2 Humble CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup ROS2 Humble
      - name: Setup ROS2 Humble
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-rosdep python3-colcon-common-extensions python3-pip
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          python3 -m pip install -U setuptools wheel black isort

      # Format Python code automatically
      - name: Auto-format Python code
        run: |
          find src test -name "*.py" | xargs python3 -m isort
          find src test -name "*.py" | xargs python3 -m black

      # Source ROS2 and build workspace
      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

      # Source workspace and run tests
      - name: Run tests
        run: |
          source install/setup.bash
          colcon test
          colcon test-result --verbose
