name: ROS2 Humble CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up ROS2 Humble manually
      - name: Install ROS2 Humble
        run: |
          sudo apt update && sudo apt install -y curl gnupg2 lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
            http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep python3-pip
          sudo rosdep init || true
          rosdep update

      # 3️⃣ Install Python dependencies
      - name: Install Python tools
        run: |
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install black isort

      # 4️⃣ Install ROS2 dependencies for your packages
      - name: Install package dependencies
        run: |
          source /opt/ros/humble/setup.bash
          rosdep install --from-paths src --ignore-src -r -y

      # 5️⃣ Auto-format code before test
      - name: Auto-format Python code
        run: |
          find src -name "*.py" | xargs python3 -m isort
          find src -name "*.py" | xargs python3 -m black

      # 6️⃣ Build your workspace
      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

      # 7️⃣ Run tests
      - name: Run tests
        run: |
          source install/setup.bash
          colcon test
          colcon test-result --verbose
