name: ROS2 Humble CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Cleanup old ROS files
        run: |
          sudo rm -f /etc/apt/sources.list.d/ros2-latest.list
          sudo rm -f $GITHUB_WORKSPACE/ros.key || true

      - name: Setup ROS2 Humble
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-rosdep python3-colcon-common-extensions
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

      - name: Run tests
        run: |
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
