name: ROS2 Humble CI + CD (Build, Test & Deploy)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # =====================================================
  # 1️⃣ CI: Build and Test ROS2 Workspace
  # =====================================================
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Fix Python packaging versions
        run: |
          pip install --upgrade pip
          pip install setuptools==69.5.1 packaging==24.0 colcon-common-extensions==0.3.0
          pip install flake8 pytest pytest-cov pytest-repeat pytest-rerunfailures

      - name: Build ROS2 workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+

      - name: Run tests
        run: |
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose || true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/**/test_results/**/*.xml

  # =====================================================
  # 2️⃣ Simulation: Headless Gazebo Check
  # =====================================================
  simulation:
    runs-on: ubuntu-22.04
    needs: build_and_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install simulation dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ros-humble-gazebo-ros-pkgs ros-humble-xacro
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build and source workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+
          source install/setup.bash

      - name: Run headless Gazebo test
        run: |
          echo "Launching Gazebo in headless mode..."
          gzserver --verbose &
          sleep 5
          if pgrep gzserver > /dev/null; then
            echo "✅ Gazebo launched successfully!"
            pkill gzserver
          else
            echo "❌ Gazebo failed to start!"
            exit 1
          fi

  # =====================================================
  # 3️⃣ CD: Build and Push Docker Image
  # =====================================================
  deploy:
    runs-on: ubuntu-22.04
    needs: simulation  # Only runs if simulation succeeded

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ros2_sim:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ros2_sim:${{ github.sha }}

      - name: Confirm image exists locally
        run: docker images | grep ros2_sim

      - name: Verify headless Gazebo in container (optional)
        run: |
          source /opt/ros/humble/setup.bash
          echo "Launching Gazebo inside container (headless)..."
          xvfb-run -a gazebo --headless -s libgazebo_ros_factory.so &
          sleep 10
          echo "✅ Gazebo launched successfully!"
